/*
  Copyright 2010-202x held jointly by participating institutions.
  Amanzi is released under the three-clause BSD License.
  The terms of use and "as is" disclaimer for this license are
  provided in the top-level COPYRIGHT file.

  Authors:
*/

#ifndef _RegType_H_
#define _RegType_H_

enum RegType { interior, exterior, periodic, refWall, inflow,
                outflow, REG_TYPE_SIZE};

#endif
