DIFF = diff
DFLAGS = --brief

GEOCHEM = ../../../build/src/chemistry/test_drivers/geochemistryTest
GEOVERB = -v 2

TESTS_CRUNCH = \
	carbonate-unit-activity-coeff-crunch \
	carbonate-debye-huckel-crunch \
	ca-carbonate-unit-activity-coeff-crunch \
	ca-carbonate-debye-huckel-crunch \
	calcite-kinetics-crunch \
	calcite-kinetics-large-time-step-crunch

TESTS_PFLOTRAN = \
	carbonate-unit-activity-coeff-pflotran \
	carbonate-debye-huckel-pflotran \
	ca-carbonate-unit-activity-coeff-pflotran \
	ca-carbonate-debye-huckel-pflotran \
	calcite-kinetics-pflotran

TESTS_FBASIN = \
	fbasin-17-initial \
	fbasin-17-infiltration \
	fbasin-17-source \
	fbasin-5-initial \
	fbasin-5-outlet \
	fbasin-5-source

#
# tests
#
all : test

tests : test

test : $(TESTS_CRUNCH) $(TESTS_PFLOTRAN) $(TESTS_FBASIN)

test-crunch : $(TESTS_CRUNCH)

test-pflotran : $(TESTS_PFLOTRAN)



#
# carbonate
#
carbonate-unit-activity-coeff-crunch  :
	@echo
	@echo ----------------------------------------
	$(GEOCHEM) -m crunch -t 1 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/crunch/$@.test
	@echo

carbonate-unit-activity-coeff-pflotran  :
	@echo
	@echo ----------------------------------------
	$(GEOCHEM) -m pflotran -t 1 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/pflotran/$@.test
	@echo

carbonate-debye-huckel-crunch  : 
	@echo
	@echo ----------------------------------------
	$(GEOCHEM) -m crunch -t 2 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/crunch/$@.test
	@echo

carbonate-debye-huckel-pflotran  : 
	@echo
	@echo ----------------------------------------
	$(GEOCHEM) -m pflotran -t 2 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/pflotran/$@.test
	@echo

#
# ca-carbonate
#
ca-carbonate-unit-activity-coeff-crunch : 
	@echo
	@echo ----------------------------------------
	$(GEOCHEM) -m crunch -t 3 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/crunch/$@.test
	@echo

ca-carbonate-debye-huckel-crunch : 
	@echo
	@echo ----------------------------------------
	$(GEOCHEM) -m crunch -t 4 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/crunch/$@.test
	@echo

ca-carbonate-unit-activity-coeff-pflotran : 
	@echo
	@echo ----------------------------------------
	$(GEOCHEM) -m pflotran -t 3 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/pflotran/$@.test
	@echo

ca-carbonate-debye-huckel-pflotran : 
	@echo
	@echo ----------------------------------------
	$(GEOCHEM) -m pflotran -t 4 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/pflotran/$@.test
	@echo

#
# calcite kinetics
#
calcite-kinetics-crunch : 
	@echo
	@echo ----- WARNING: These results have not been verified! -----
	$(GEOCHEM) -m crunch -t 5 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/crunch/$@.test
	@echo

calcite-kinetics-large-time-step-crunch : 
	@echo
	@echo ----- WARNING: These results have not been verified! -----
	$(GEOCHEM) -m crunch -t 10 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/crunch/$@.test
	@echo

calcite-kinetics-pflotran : 
	@echo
	@echo ----- WARNING: These results have not been verified! -----
	$(GEOCHEM) -m pflotran -t 5 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/pflotran/$@.test
	@echo

#
# fbasin
#
fbasin-17-initial : 
	@echo
	@echo ----- WARNING: These results have not been verified! -----
	$(GEOCHEM) -m crunch -t 7 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/crunch/$@.test
	@echo

fbasin-17-infiltration : 
	@echo
	@echo ----- WARNING: These results have not been verified! -----
	$(GEOCHEM) -m crunch -t 8 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/crunch/$@.test
	@echo

fbasin-17-source : 
	@echo
	@echo ----- WARNING: These results have not been verified! -----
	$(GEOCHEM) -m crunch -t 9 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/crunch/$@.test
	@echo

fbasin-5-initial : 
	@echo
	@echo ----- WARNING: These results have not been verified! -----
	$(GEOCHEM) -m crunch -t 13 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/crunch/$@.test
	@echo

fbasin-5-outlet : 
	@echo
	@echo ----- WARNING: These results have not been verified! -----
	$(GEOCHEM) -m crunch -t 14 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/crunch/$@.test
	@echo

fbasin-5-source : 
	@echo
	@echo ----- WARNING: These results have not been verified! -----
	$(GEOCHEM) -m crunch -t 15 $(GEOVERB) > $@.cout
	-$(DIFF) $(DFLAGS) $@.cout results/crunch/$@.test
	@echo


#
# clean - Clean up the directory.
#
clean : 
	rm -f *~ *.CKP *.ln *.BAK *.bak .*.bak \
		*.cout \
		core errs \
		,* .emacs_* \
		tags TAGS \
		make.log MakeOut

#
# clobber - Really clean up the directory.
#
clobber : clean 
	rm -f .Makedepend *.o *.il $(EXECUTABLES) $(LIBRARIES)

#
# FORCE - Null rule to force things to happen.
#
FORCE :
