/*
 * THIS FILE WAS GENERATED BY make_defines DO NOT EDIT
*/

#if !defined(_ats_source) && !defined(_include_ats_h)
#error "Error: do not include this file directly, use #include <ats.h>"
#endif

#ifndef ats_defines_h
#define ats_defines_h

static const int32_t ATS_SUCCESS = 0;
static const int32_t ATS_MPI_ERROR = -1;

#endif // ats_defines_h
