FROM metsi/amanzi-tpls:latest
LABEL Description="This image builds Amanzi from the latest version of the Amanzi TPLs contained in a Docker image"

USER amanzi_user

WORKDIR /home/amanzi_user/amanzi
RUN git pull

ENV LD_LIBRARY_PATH=/home/amanzi_user/local/tpls/lib:/home/amanzi_user/local/tpls/petsc-3.7.5/lib:/home/amanzi_user/local/tpls/trilinos-12-10-1/lib:/home/amanzi_user/local/tpls/SEACAS/lib:$LD_LIBRARY_PATH

RUN ./bootstrap.sh --prefix=/home/amanzi_user/local \
   --amanzi-build-dir=/home/amanzi_user/amanzi_builddir/amanzi \
   --tpl-config-file=/home/amanzi_user/local/tpls/share/cmake/amanzi-tpl-config.cmake \
   --parallel=8 \
   --disable-structured \
   --with-mpi=/usr \
   --enable-shared \
   && cd /home/amanzi_user/amanzi_builddir/amanzi \
   && make test 

