FROM metsi/amanzi-tpls:0.94.12
LABEL Description="Amanzi: Build stage 1 and install in temporary Docker image."

# Switch to amanzi_user
USER amanzi_user

# Change the Working Directory and update amanzi
WORKDIR /home/amanzi_user/amanzi
RUN git pull
  
RUN ./bootstrap.sh --prefix=${AMANZI_PREFIX} \
   --amanzi-build-dir=/home/amanzi_user/amanzi_builddir/amanzi \
   --tpl-config-file=${AMANZI_TPLS_DIR}/share/cmake/amanzi-tpl-config.cmake \
   --parallel=4 --opt \
   --disable-structured \
   --enable-alquimia --enable-pflotran --enable-crunchtope \
   --with-mpi=/usr \
   --enable-shared \
   --enable-build_stage_1


