FROM metsi/amanzi-tpls:latest
LABEL Description="This image builds Amanzi from the latest version of the Amanzi TPLs contained in a Docker image"

USER amanzi_user

WORKDIR /home/amanzi_user/amanzi
RUN git pull
RUN ./bootstrap.sh --prefix=/home/amanzi_user/local --amanzi-build-dir=/home/amanzi_user/amanzi_builddir/amanzi --tpl-config-file=/home/amanzi_user/local/tpls/share/cmake/amanzi-tpl-config.cmake --parallel=8
