ARG amanzi_tpls_ver=latest
ARG mpi_flavor=mpich
FROM metsi/amanzi-tpls:${amanzi_tpls_ver}-${mpi_flavor}
LABEL Description="ATS CI: Build ATS in a Docker image."

# Switch to amanzi_user
USER amanzi_user

RUN echo "${AMANZI_PREFIX}"
RUN echo "${AMANZI_TPLS_DIR}"

# Arguments
ARG amanzi_branch=master
ARG ats_branch=master
ARG ats_regression_branch=master
ARG https_proxy=
ARG http_proxy=

# Optional: User can specify a proxy
ENV https_proxy=$https_proxy \
    http_proxy=$http_proxy

# Change the Working Directory and update amanzi
WORKDIR /home/amanzi_user/amanzi

# Make sure we have updated branch information
RUN echo "Amanzi branch = $amanzi_branch"
RUN git pull
RUN git branch --list

# Checkout the branch and update it
RUN git checkout $amanzi_branch
RUN git pull
RUN git rev-parse --short HEAD

# Checkout/update the submodules
RUN git submodule update --init --recursive
WORKDIR /home/amanzi_user/amanzi/src/physics/ats
RUN git checkout $ats_branch
RUN git pull
RUN git rev-parse --short HEAD
WORKDIR /home/amanzi_user/amanzi/src/physics/ats/testing/ats-regression-tests
RUN git checkout master
RUN git pull
RUN git checkout $ats_regression_branch
RUN git pull
RUN git rev-parse --short HEAD
WORKDIR /home/amanzi_user/amanzi

ENV AMANZI_SRC_DIR=/home/amanzi_user/amanzi \
    ATS_SRC_DIR=/home/amanzi_user/amanzi/src/physics/ats 
  
RUN ./bootstrap.sh --prefix=${AMANZI_PREFIX} \
   --amanzi-build-dir=/home/amanzi_user/amanzi_builddir/ats \
   --tpl-config-file=${AMANZI_TPLS_DIR}/share/cmake/amanzi-tpl-config.cmake \
   --branch=$amanzi_branch \
   --branch_ats=$ats_branch \
   --parallel=4 \
   --opt \
   --with-mpi=/usr \
   --with-python=/usr/bin/python \
   --enable-shared \
   --disable-structured \
   --disable-build_user_guide \
   --enable-geochemistry \
   --disable-amanzi_physics \
   --enable-ats_physics \
   --enable-reg_tests \
   && cd /home/amanzi_user/amanzi_builddir/ats \
   && make test \
   && rm -r /home/amanzi_user/amanzi_builddir/

# Set path to make it easier to run amanzi
ENV PATH=/home/amanzi_user/install/bin:${PATH}
RUN echo $PATH

# Create mount point for work on the host
RUN mkdir /home/amanzi_user/work

# Unset proxy
ENV https_proxy= \
    http_proxy= 
