#!/bin/bash

#
#  Run ATS in docker container
#
#  Customize as you like, this is a simple example and assumes you want to run
#  in your current / present working directory:
#
#  --mount provides the mount type,source, and target, e.g.,
#          --mount type=bind,source=mount_point_on_host,target=mount_point_on_container
#  -w      sets current working directory on the container
#  -it     -i and -t together provide an interactive terminal (a tty) for the container
#  -p      map host_port:container_port, e.g., -p 8899:8899 
#  --rm    deletes the container on exit
#
#  There's not effort here to parse arguments.  Just assumes you are providing an xml file.
#

#  We recommend that the current pwd is the top-level of your desired workspace.
#
HOST_MNT=`pwd -P`

#  On the container, we recommend your mount point is the short-course directory and that
#  is also your PWD on startup.
#
CONT_MNT=/home/amanzi_user/work
CONT_PWD=/home/amanzi_user/work

docker run -it --mount type=bind,source=$HOST_MNT,target=$CONT_MNT -w $CONT_PWD metsi/ats:master-latest /bin/bash

