/*
  Mesh Factory 

  Copyright 2010-201x held jointly by LANS/LANL, LBNL, and PNNL. 
  Amanzi is released under the three-clause BSD License. 
  The terms of use and "as is" disclaimer for this license are 
  provided in the top-level COPYRIGHT file.

  Author: William A. Perkins
*/

#ifndef AMANZI_FRAMEWORK_TRAITS_HH_
#define AMANZI_FRAMEWORK_TRAITS_HH_

#include <AmanziComm.hh>
#include <Teuchos_RCP.hpp>
#include <Teuchos_ParameterList.hpp>

#include "MeshFramework.hh"
#include "MeshFileType.hh"
#include "MeshDefs.hh"
#include "Mesh.hh"

#include "GeometricModel.hh"

#include "errors.hh"
#include "exceptions.hh"
#include "VerboseObject.hh"

namespace Amanzi {
namespace AmanziMesh {

// Is the specified framework available
bool framework_available(const Framework& f);

// General routine to see if a format can be read by particular framework
bool framework_reads(const Framework& f, const Format& fmt, const bool& parallel);

// Read a mesh
Teuchos::RCP<Mesh> 
framework_read(const Comm_ptr_type& comm_,
               const Framework& f, 
               const std::string& fname,
               const Teuchos::RCP<const AmanziGeometry::GeometricModel>& gm =  Teuchos::null,
               const Teuchos::RCP<const Teuchos::ParameterList>& plist = Teuchos::null,
               const bool request_faces = true,
               const bool request_edges = false);

// General routine to see if a mesh can be generated by a particular framework
bool framework_generates(const Framework& f, const bool& parallel, const unsigned int& dimension);

// Generate a hexahedral mesh
Teuchos::RCP<Mesh> 
framework_generate(const Comm_ptr_type& comm_, const Framework& f, 
                   const double& x0, const double& y0, const double& z0,
                   const double& x1, const double& y1, const double& z1,
                   const unsigned int& nx, const unsigned int& ny, 
                   const unsigned int& nz,
                   const Teuchos::RCP<const AmanziGeometry::GeometricModel>& gm = Teuchos::null,
                   const Teuchos::RCP<const Teuchos::ParameterList>& plist = Teuchos::null,
                   const bool request_faces = true,
                   const bool request_edges = false);

// Generate a quadrilateral mesh
Teuchos::RCP<Mesh> 
framework_generate(const Comm_ptr_type& comm_, const Framework& f, 
                   const double& x0, const double& y0,
                   const double& x1, const double& y1,
                   const unsigned int& nx, const unsigned int& ny,
                   const Teuchos::RCP<const AmanziGeometry::GeometricModel>& gm = Teuchos::null,
                   const Teuchos::RCP<const Teuchos::ParameterList>& plist = Teuchos::null,
                   const bool request_faces = true,
                   const bool request_edges = false);

// General routine to see if a mesh can be extracted from another mesh by a particular framework
bool framework_extracts(const Framework& f, const bool& parallel, const unsigned int& dimension);

Teuchos::RCP<Mesh>
framework_extract(const Comm_ptr_type& comm_, const Framework& f,
                  const Teuchos::RCP<const Mesh>& inmesh,
                  const Entity_ID_List& setnames,
                  const Entity_kind setkind,
                  const bool flatten = false,
                  const bool extrude = false,
                  const bool request_faces = true,
                  const bool request_edges = false);

} // namespace AmanziMesh
} // namespace Amanzi

#endif
