#  -*- mode: cmake -*-
#
# Build TPL: XSDK using Spack
#  

# --- Define all the directories and common external project flags
if ( BUILD_SPACK )
    define_external_project_args(XSDK
	TARGET xsdk
	BUILD_IN_SOURCE 
	DEPENDS SPACK )
else()
    define_external_project_args(XSDK
	TARGET xsdk
	BUILD_IN_SOURCE )
endif()

# add version version to the autogenerated tpl_versions.h file
amanzi_tpl_version_write(FILENAME ${TPL_VERSIONS_INCLUDE_FILE}
    PREFIX XSDK
    VERSION 0 2 0 )

ExternalProject_Add(${XSDK_BUILD_TARGET}
    
    # The following 2 lines are only here because CMake will not allow
    # a build without at least these two variables defined (and BUILD_COMMAND).
    # However, they serve no real purpose for this particular build.
    DOWNLOAD_COMMAND ls
    
    CONFIGURE_COMMAND ls
    
    BUILD_COMMAND ${SPACK_BINARY} install xsdk 
    
    INSTALL_COMMAND ${SPACK_BINARY} view symlink ${TPL_INSTALL_PREFIX} xsdk 
)

