#  -*- mode: cmake -*-
#
# Build TPL:  EcoSIM
# This builds the BGC code EcoSIM for use within ATS
#
# --- Define all the directories and common external project flags

define_external_project_args(ECOSIM
                             TARGET ecosim
                             DEPENDS HDF5 ZLIB NetCDF NetCDF_Fortran)

# add version to the autogenerated tpl_versions.h file
amanzi_tpl_version_write(FILENAME ${TPL_VERSIONS_INCLUDE_FILE}
  PREFIX ECOSIM
  VERSION ${ECOSIM_VERSION_MAJOR} ${ECOSIM_VERSION_MINOR} ${ECOSIM_VERSION_PATCH})

message(STATUS "AG: >>>>>> Building EcoSIM: ")

# --- If downloads are disabled point to local repository
if ( DISABLE_EXTERNAL_DOWNLOAD )
  STRING(REGEX REPLACE "/src/master" "" GIT_REPOSITORY_TEMP ${ECOSIM_GIT_REPOSITORY})
  STRING(REGEX REPLACE ".*\/" "" ECOSIM_GIT_REPOSITORY_LOCAL_DIR ${GIT_REPOSITORY_TEMP})
  set (ECOSIM_GIT_REPOSITORY_TEMP ${TPL_DOWNLOAD_DIR}/${ECOSIM_GIT_REPOSITORY_LOCAL_DIR})
else()
  set (ECOSIM_GIT_REPOSITORY_TEMP ${ECOSIM_GIT_REPOSITORY})
endif()

# Set EcoSIM install prefix
set(ECOSIM_INSTALL_PREFIX ${TPL_INSTALL_PREFIX}/ecosim)

# determine library type
if (BUILD_SHARED_LIBS)
  set(ECOSIM_LIBS_TYPE "SHARED")
else()
  set(ECOSIM_LIBS_TYPE "STATIC")
endif()

# Set TPL library paths (HDF5, NetCDF)
include(BuildLibraryName)
build_library_name(netcdf ecosim_netcdf_library ${ECOSIM_LIBS_TYPE} APPEND_PATH ${NetCDF_DIR}/lib)
build_library_name(netcdff ecosim_netcdff_library ${ECOSIM_LIBS_TYPE} APPEND_PATH ${NetCDF_DIR}/lib)
if ( ${CMAKE_BUILD_TYPE} STREQUAL "Debug" )
  build_library_name(hdf5_hl_debug ecosim_hdf5_hl_library ${ECOSIM_LIBS_TYPE} APPEND_PATH ${TPL_INSTALL_PREFIX}/lib)
  build_library_name(hdf5_debug ecosim_hdf5_library ${ECOSIM_LIBS_TYPE} APPEND_PATH ${TPL_INSTALL_PREFIX}/lib)
else()
  build_library_name(hdf5_hl ecosim_hdf5_hl_library ${ECOSIM_LIBS_TYPE} APPEND_PATH ${HDF5_DIR}/lib)
  build_library_name(hdf5 ecosim_hdf5_library ${ECOSIM_LIBS_TYPE} APPEND_PATH ${HDF5_DIR}/lib)
endif()
build_library_name(z ecosim_z_library ${ECOSIM_LIBS_TYPE} APPEND_PATH ${ZLIB_DIR}/lib)

set(ecosim_netcdf_libraries
       ${ecosim_netcdf_library}
       ${ecosim_hdf5_hl_library}
       ${ecosim_hdf5_library} -ldl
       ${ecosim_z_library})

# Set EcoSIM CMake cache arguments
# >>> Note the HDF5 includes and libraries include the zlib, math (-lm), and dynamic link library (-ldl)
set(ECOSIM_CMAKE_CACHE_ARGS
      "-DCMAKE_INSTALL_PREFIX:FILEPATH=${ECOSIM_INSTALL_PREFIX}"
      "-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}"
      "-DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}"
      "-DTPLS_NETCDF_INCLUDE_DIRS=${NetCDF_INCLUDE_DIRS}"
      "-DTPLS_NETCDF_LIBRARIES:STRING=${NetCDF_C_LIBRARIES}"
      "-DTPLS_NETCDF_FORTRAN_INCLUDE_DIRS:STRING=${NetCDF_FORTRAN_INCLUDE_DIRS}"
      "-DTPLS_NETCDF_FORTRAN_LIBRARIES:STRING=${NetCDF_FORTRAN_LIBRARIES}"
      "-DTPLS_HDF5_INCLUDE_DIRS=${HDF5_INCLUDE_DIRS}"
      "-DTPLS_HDF5_LIBRARIES:STRING=${HDF5_LIBRARIES}"
)

# --- Patch the original code
# set(ECOSIM_patch_file ecosim-cmake.patch)
# New approach: Updating EcoSIM CMake directly on a fork (branch: david/cmake-updates).
set(ECOSIM_patch_file )

patch_tpl(ECOSIM
          ${ECOSIM_prefix_dir}
          ${ECOSIM_source_dir}
          ${ECOSIM_stamp_dir}
          ECOSIM_patch_file)

    
# --- Explicitly set ATS_ECOSIM as this is needed in EcoSIM CMake to trigger use of ATS external libraries
list(APPEND ECOSIM_CMAKE_CACHE_ARGS "-DATS_ECOSIM:BOOL=1")

# --- Define ECOSIM_FCFLAGS to augment AMANZI_COMMON_FCFLAGS
build_whitespace_string(ECOSIM_FCFLAGS ${Amanzi_COMMON_FCFLAGS} -Wno-unused-variable)

# --- Override minimum version
if(CMAKE_MAJOR_VERSION VERSION_EQUAL "4")
  list(APPEND ECOSIM_CMAKE_CACHE_ARGS "-DCMAKE_POLICY_VERSION_MINIMUM:STRING=3.5")
endif()


# --- Add external project build and tie to the EcoSIM build target
ExternalProject_Add(${ECOSIM_BUILD_TARGET}
                    DEPENDS   ${ECOSIM_PACKAGE_DEPENDS}        # Package dependency target
                    PREFIX    ${ECOSIM_prefix_dir}
                    TMP_DIR   ${ECOSIM_tmp_dir}                # Temporary files directory
                    STAMP_DIR ${ECOSIM_stamp_dir}              # Timestamp and log directory
                    # -- Download and URL definitions
                    DOWNLOAD_DIR  ${TPL_DOWNLOAD_DIR}  
                    # -- Note: The repo is cloned into the ${ECOSIM_source_dir} directory
                    GIT_REPOSITORY ${ECOSIM_GIT_REPOSITORY_TEMP}
                    GIT_TAG        ${ECOSIM_GIT_TAG}
                    # -- Update (one way to skip this step is use null command)
                    UPDATE_COMMAND ""
                    # -- Patch
                    PATCH_COMMAND ${ECOSIM_PATCH_COMMAND}
                    # -- Configure
                    SOURCE_DIR    ${ECOSIM_source_dir}         # Source directory
                    CMAKE_ARGS    ${AMANZI_CMAKE_CACHE_ARGS}     # Ensure uniform build
                                  ${ECOSIM_CMAKE_CACHE_ARGS}
                                  -DCMAKE_C_FLAGS:STRING=${Amanzi_COMMON_CFLAGS}  # Ensure uniform build
                                  -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
                                  -DCMAKE_CXX_FLAGS:STRING=${Amanzi_COMMON_CXXFLAGS}  # Ensure uniform build
                                  -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
                                  -DCMAKE_Fortran_FLAGS:STRING=${ECOSIM_FCFLAGS} # Not sure this customization is necessary
                                  -DCMAKE_Fortran_COMPILER:FILEPATH=${CMAKE_Fortran_COMPILER}
                    # -- Build
                    BINARY_DIR       ${ECOSIM_build_dir}           # Build directory 
                    BUILD_COMMAND    $(MAKE)                       # $(MAKE) enables parallel builds through make
                    BUILD_IN_SOURCE  ${ECOSIM_BUILD_IN_SOURCE}     # Flag for in source builds
                    # -- Install
                    INSTALL_DIR      ${TPL_INSTALL_PREFIX}/ecosim  # Install directory, NOT in the usual place!
                    # -- Output control
                    ${ECOSIM_logging_args})


# --- Useful variables for packages that depend on EcoSIM
#
#   - things to consider is RPATH being set correctly
#   - are we installing mod files in a good location (e.g., ${TPL_INSTALL_PREFIX}/ecosim/include)
#   - sometimes there's additional "install_prefix" directories to define
#
set(ECOSIM_DIR ${TPL_INSTALL_PREFIX}/ecosim)

