#  -*- mode: cmake -*-

#
# Build TPL: COOLPROP
#   
# --- Define all the directories and common external project flags
define_external_project_args(COOLPROP
                             TARGET coolprop
                             DEPENDS )

# add version to the autogenerated tpl_versions.h file
include(${SuperBuild_SOURCE_DIR}/TPLVersions.cmake)
amanzi_tpl_version_write(FILENAME ${TPL_VERSIONS_INCLUDE_FILE}
                         PREFIX COOLPROP
                         VERSION ${ALQUIMIA_VERSION_MAJOR} ${ALQUIMIA_VERSION_MINOR} ${ALQUIMIA_VERSION_PATCH})

# --- Patch the original code
set(COOLPROP_patch_file coolprop-cmake.patch)
patch_tpl(COOLPROP
          ${COOLPROP_prefix_dir}
          ${COOLPROP_source_dir}
          ${COOLPROP_stamp_dir}
          COOLPROP_patch_file)

# --- Define the arguments passed to CMake.
set(COOLPROP_INSTALL_PREFIX ${TPL_INSTALL_PREFIX}/coolprop)

set(COOLPROP_CMAKE_ARGS 
      "-DCMAKE_INSTALL_PREFIX:FILEPATH=${COOLPROP_INSTALL_PREFIX}"
      "-DCMAKE_INSTALL_RPATH:FILEPATH=${COOLPROP_INSTALL_PREFIX}"
      "-DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=FALSE"
      "-DCMAKE_SKIP_BUILD_RPATH:BOOL=FALSE"
      "-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE"
      "-DCMAKE_INSTALL_NAME_DIR=${COOLPROP_INSTALL_PREFIX}/lib"
      "-DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}"
      "-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}"
      "-DCOOLPROP_SHARED_LIBRARY:BOOL=ON"
      "-DCOOLPROP_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/coolprop"
      "-DMPI_PREFIX=${MPI_PREFIX}")

# --- Override minimum version
if(CMAKE_MAJOR_VERSION VERSION_EQUAL "4")
  list(APPEND COOLPROP_CMAKE_ARGS "-DCMAKE_POLICY_VERSION_MINIMUM:STRING=3.5")
endif()

# --- Add external project build and tie to the COOLPROP build target
ExternalProject_Add(${COOLPROP_BUILD_TARGET}
                    DEPENDS   ${COOLPROP_PACKAGE_DEPENDS}         # Package dependency target
                    TMP_DIR   ${COOLPROP_tmp_dir}                 # Temporary files directory
                    STAMP_DIR ${COOLPROP_stamp_dir}               # Timestamp and log directory
                    # -- Download and GIT definition
                    GIT_REPOSITORY ${COOLPROP_GIT_REPOSITORY}              
                    GIT_TAG        ${COOLPROP_GIT_TAG}   
                    # -- Patch
                    PATCH_COMMAND ${COOLPROP_PATCH_COMMAND}       # Mods to source
                    # -- Configure
                    SOURCE_DIR    ${COOLPROP_source_dir}          # Source directory
                    CMAKE_ARGS    ${AMANZI_CMAKE_CACHE_ARGS}      # Ensure uniform build
                                  ${COOLPROP_CMAKE_ARGS}
                                  -DCMAKE_C_FLAGS:STRING=${Amanzi_COMMON_CFLAGS}  # Ensure uniform build
                                  -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
                                  -DCMAKE_CXX_FLAGS:STRING=${Amanzi_COMMON_CXXFLAGS}  # Ensure uniform build
                                  -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
                    # -- Build
                    BINARY_DIR       ${COOLPROP_build_dir}        # Build directory 
                    BUILD_COMMAND    $(MAKE)
                    # -- Install
                    INSTALL_DIR      ${COOLPROP_INSTALL_PREFIX}   # Install directory
                    INSTALL_COMMAND  $(MAKE) install
                    # -- Output control
                    ${COOLPROP_logging_args})

include(BuildLibraryName)
build_library_name(coolprop COOLPROP_LIB APPEND_PATH ${COOLPROP_INSTALL_PREFIX}/lib)
