#  -*- mode: cmake -*-

#
# Build TPL: MOAB 
# 
# --- Define all the directories and common external project flags
define_external_project_args(MOAB 
                             TARGET moab
                             DEPENDS ZLIB HDF5 NetCDF)

# add version version to the autogenerated tpl_versions.h file
amanzi_tpl_version_write(FILENAME ${TPL_VERSIONS_INCLUDE_FILE}
                         PREFIX MOAB
                         VERSION ${MOAB_VERSION_MAJOR} ${MOAB_VERSION_MINOR} ${MOAB_VERSION_PATCH})

# --- Configure the package
set(MOAB_CMAKE_CACHE_ARGS "-DENABLE_MPI:BOOL=FALSE")
list(APPEND MOAB_CMAKE_CACHE_ARGS "-DENABLE_ZLIB:BOOL=TRUE")
list(APPEND MOAB_CMAKE_CACHE_ARGS "-DENABLE_HDF5:BOOL=TRUE")
list(APPEND MOAB_CMAKE_CACHE_ARGS "-DENABLE_NETCDF:BOOL=TRUE")
list(APPEND MOAB_CMAKE_CACHE_ARGS "-DENABLE_METIS:BOOL=TRUE")
list(APPEND MOAB_CMAKE_CACHE_ARGS "-DENABLE_PARMETIS:BOOL=TRUE")
#list(APPEND MOAB_CMAKE_CACHE_ARGS "-DENABLE_ZOLTAN:BOOL=TRUE")
list(APPEND MOAB_CMAKE_CACHE_ARGS "-DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}")

# location of package
list(APPEND MOAB_CMAKE_CACHE_ARGS "-DNETCDF_ROOT:PATH=${TPL_INSTALL_PREFIX}")
list(APPEND MOAB_CMAKE_CACHE_ARGS "-DMETIS_DIR:PATH=${TPL_INSTALL_PREFIX}")
list(APPEND MOAB_CMAKE_CACHE_ARGS "-DPARMETIS_DIR:PATH=${TPL_INSTALL_PREFIX}")
#list(APPEND MOAB_CMAKE_CACHE_ARGS "-DZOLTAN_DIR:PATH=${Zoltan_INSTALL_PREFIX}")

# --- Add external project build and tie to the ZLIB build target
ExternalProject_Add(${MOAB_BUILD_TARGET}
                    DEPENDS   ${MOAB_PACKAGE_DEPENDS}      # Package dependency target
                    TMP_DIR   ${MOAB_tmp_dir}              # Temporary files directory
                    STAMP_DIR ${MOAB_stamp_dir}            # Timestamp and log directory
                    # -- Download and URL definitions
                    DOWNLOAD_DIR ${TPL_DOWNLOAD_DIR}       
                    URL          ${MOAB_URL}               # URL may be a web site OR a local file
                    URL_MD5      ${MOAB_MD5_SUM}           # md5sum of the archive file
                    # -- Configure
                    SOURCE_DIR   ${MOAB_source_dir}        # Source directory
                    CMAKE_CACHE_ARGS ${AMANZI_CMAKE_CACHE_ARGS}   # Global definitions from root CMakeList
                                     ${MOAB_CMAKE_CACHE_ARGS}
                                     -DCMAKE_C_FLAGS:STRING=${Amanzi_COMMON_CFLAGS}  # Ensure uniform build
                                     -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
                                     -DCMAKE_CXX_FLAGS:STRING=${Amanzi_COMMON_CXXFLAGS}
                                     -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
                    # -- Build
                    BINARY_DIR        ${MOAB_build_dir}           # Build directory 
                    BUILD_COMMAND     $(MAKE)                     # $(MAKE) enables parallel builds through make
                    BUILD_IN_SOURCE   ${MOAB_BUILD_IN_SOURCE}     # Flag for in source builds
                    # -- Install
                    INSTALL_DIR      ${TPL_INSTALL_PREFIX}        # Install directory
                    # -- Output control
                    ${MOAB_logging_args})
