#  -*- mode: cmake -*-
#
# Build TPL: XERCES using Spack
#  

# -- Define all the directories and common external project flags
define_external_project_args(XERCES 
    TARGET xerces
        BUILD_IN_SOURCE
        DEPENDS ${MPI_PROJECT} )
#set(ENV{PACKAGE} xerces-c)
#set(ENV{SPACK_BINARY} ${SPACK_BINARY})
#  include(${Amanzi_SOURCE_DIR}/tools/cmake/SpackFunctions.cmake) 

# add version version to the autogenerated tpl_versions.h file
#  amanzi_tpl_version_write(FILENAME ${TPL_VERSIONS_INCLUDE_FILE}
#      PREFIX XERCES
#      VERSION ${XERCES_VERSION_MAJOR} ${XERCES_VERSION_MINOR} ${XERCES_VERSION_PATCH})
#
ExternalProject_Add(${XERCES_BUILD_TARGET} # Xerces
    
    # The following 3 lines are only here because CMake will not allow
    # a build without at least these three variables defined.
    # However, they serve no real purpose for this particular build.
    DOWNLOAD_COMMAND ls
    
    CONFIGURE_COMMAND ls
    
    BUILD_COMMAND ${SPACK_BINARY} install xerces-c 
    
    INSTALL_COMMAND  ${SPACK_BINARY} view symlink ${TPL_INSTALL_PREFIX} xerces-c 
    #INSTALL_COMMAND  ${SuperBuild_BUILD_FILES_DIR}/spack_generic_build.sh ${SPACK_BINARY} xerces-c ${TPL_INSTALL_PREFIX} 
    #INSTALL_COMMAND ${CMAKE_COMMAND} -P ${Amanzi_SOURCE_DIR}/tools/cmake/SpackFunctions.cmake
)

#build_library_name(xerces-c XERCES_LIBRARY APPEND_PATH ${TMP_SPACK_INSTALL_DIR}/lib)
build_library_name(xerces-c XERCES_LIBRARY APPEND_PATH ${TPL_INSTALL_PREFIX}/lib)

set(XERCES_LIBRARIES ${XERCES_LIBRARY})
#set(XERCES_INCLUDE_DIRS ${TMP_SPACK_INSTALL_DIR}/include)
#set(XERCES_INSTALL_PREFIX ${TMP_SPACK_INSTALL_DIR})
set(XERCES_INCLUDE_DIRS ${TPL_INSTALL_PREFIX}/include)
set(XERCES_INSTALL_PREFIX ${TPL_INSTALL_PREFIX})
append_set(Amanzi_TPL_CMAKE_ARGS
    -DXERCES_DIR:FILEPATH=${XERCES_INSTALL_PREFIX})

amanzi_tpl_version_write(FILENAME ${TPL_VERSIONS_INCLUDE_FILE}
    PREFIX XERCES
    VERSION ${TMP_SPACK_VERSION} )

#  unset(TMP_SPACK_INSTALL_DIR)
#  unset(TMP_SPACK_VERSION)
#  unset(ENV{PACKAGE})
#  unset(ENV{SPACK_BINARY})
