#  -*- mode: cmake -*-

#
# Build TPL:  FMT 
#   
# --- Define all the directories and common external project flags
define_external_project_args(FMT
                             TARGET fmt
                             BUILD_IN_SOURCE)


# add version version to the autogenerated tpl_versions.h file
amanzi_tpl_version_write(FILENAME ${TPL_VERSIONS_INCLUDE_FILE}
  PREFIX FMT
  VERSION ${FMT_VERSION_MAJOR} ${FMT_VERSION_MINOR} ${FMT_VERSION_PATCH})

# --- Define the CMake configure parameters
# Note:
#      CMAKE_CACHE_ARGS requires -DVAR:<TYPE>=VALUE syntax
#      CMAKE_ARGS -DVAR=VALUE OK
# NO WHITESPACE between -D and VAR. Parser blows up otherwise.
set(FMT_CMAKE_CACHE_ARGS
                  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
                  -DCMAKE_INSTALL_PREFIX:PATH=${TPL_INSTALL_PREFIX}
                  -DBUILD_SHARED_LIBS:BOOL=TRUE
                  -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=TRUE)

# --- Add external project build and tie to the FMT build target
ExternalProject_Add(${FMT_BUILD_TARGET}
                    DEPENDS   ${FMT_PACKAGE_DEPENDS}             # Package dependency target
                    TMP_DIR   ${FMT_tmp_dir}                     # Temporary files directory
                    STAMP_DIR ${FMT_stamp_dir}                   # Timestamp and log directory
                    # -- Download and URL definitions
                    DOWNLOAD_DIR ${TPL_DOWNLOAD_DIR}              # Download directory
                    URL          ${FMT_URL}                      # URL may be a web site OR a local file
                    URL_MD5      ${FMT_MD5_SUM}                  # md5sum of the archive file
                    # -- Configure
                    SOURCE_DIR       ${FMT_source_dir}
                    CMAKE_CACHE_ARGS ${AMANZI_CMAKE_CACHE_ARGS}   # Ensure uniform build
                                     ${FMT_CMAKE_CACHE_ARGS}
                                     -DCMAKE_C_FLAGS:STRING=${Amanzi_COMMON_CFLAGS}  # Ensure uniform build
                                     -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
                    # -- Build
                    BINARY_DIR       ${FMT_build_dir}            # Build directory 
                    BUILD_COMMAND    $(MAKE)                      # $(MAKE) enables parallel builds through make
                    BUILD_IN_SOURCE  ${FMT_BUILD_IN_SOURCE}      # Flag for in source builds
                    # -- Install
                    INSTALL_DIR      ${TPL_INSTALL_PREFIX}        # Install directory
                    # -- Output control
                    ${FMT_logging_args})

# --- Useful variables that depend on ZlIB (HDF5, NetCDF)
include(BuildLibraryName)
build_library_name(fmt FMT_LIBRARIES APPEND_PATH ${TPL_INSTALL_PREFIX}/lib)
set(FMT_DIR ${TPL_INSTALL_PREFIX})
set(FMT_INCLUDE_DIRS ${TPL_INSTALL_PREFIX}/include)
