#  -*- mode: cmake -*-

#
# Build TPL:  Silo
#    
# --- Define all the directories and common external project flags
define_external_project_args(Silo TARGET silo DEPENDS ${MPI_PROJECT} HDF5 BUILD_IN_SOURCE)

# add Silo version to the autogenerated tpl_versions.h file
amanzi_tpl_version_write(FILENAME ${TPL_VERSIONS_INCLUDE_FILE}
  PREFIX Silo
  VERSION ${Silo_VERSION_MAJOR} ${Silo_VERSION_MINOR} ${Silo_VERSION_PATCH})
  

# --- Define configure parameters

# Use the common cflags, cxxflags
include(BuildWhitespaceString)
build_whitespace_string(silo_cflags
                       ${Amanzi_COMMON_CFLAGS})

build_whitespace_string(silo_cxxflags
                       ${Amanzi_COMMON_CXXFLAGS})
set(cpp_flag_list 
    ${Amanzi_COMMON_CFLAGS}
    ${Amanzi_COMMON_CXXFLAGS})
list(REMOVE_DUPLICATES cpp_flag_list)
build_whitespace_string(silo_cppflags ${cpp_flags_list})

build_whitespace_string(silo_fcflags
                       ${Amanzi_COMMON_FCFLAGS})


# Silo install directory
set(silo_install_dir ${TPL_INSTALL_PREFIX})

if (BUILD_SHARED_LIBS)
    set(CONFIG_SILO_SHARED --enable-shared=1)
else()
    set(CONFIG_SILO_SHARED --enable-shared=0)
endif()

# --- Add external project build 
ExternalProject_Add(${Silo_BUILD_TARGET}
                    DEPENDS   ${Silo_PACKAGE_DEPENDS}             # Package dependency target
                    TMP_DIR   ${Silo_tmp_dir}                     # Temporary files directory
                    STAMP_DIR ${Silo_stamp_dir}                   # Timestamp and log directory
                    # -- Download and URL definitions
                    DOWNLOAD_DIR ${TPL_DOWNLOAD_DIR}               # Download directory
                    URL          ${Silo_URL}                      # URL may be a web site OR a local file
                    URL_MD5      ${Silo_MD5_SUM}                  # md5sum of the archive file
                    # -- Configure
                    SOURCE_DIR        ${Silo_source_dir}          # Source directory
                    CONFIGURE_COMMAND
                              <SOURCE_DIR>/configure
                                          ${CONFIG_SILO_SHARED}
                                          --prefix=<INSTALL_DIR>
                                          --with-x=0
                                          --with-hdf5=${TPL_INSTALL_PREFIX}/include,${TPL_INSTALL_PREFIX}/lib
                                          --enable-fortran=0
                                          FC=${CMAKE_Fortran_COMPILER_USE}
                                          CC=${CMAKE_C_COMPILER_USE}
                                          CXX=${CMAKE_CXX_COMPILER_USE}
                                          CFLAGS=${silo_cflags}
                                          CXXFLAGS=${silo_cxxflags}
                                          
                    # -- Build
                    BINARY_DIR        ${Silo_build_dir}           # Build directory 
                    BUILD_COMMAND     $(MAKE) -j 1 SILO_DIR=${Silo_source_dir} # Run the CMake script to build
                    BUILD_IN_SOURCE   ${Silo_BUILD_IN_SOURCE}     # Flag for in source builds
                    # -- Install
                    INSTALL_DIR       ${silo_install_dir}  # Install directory, NOT in the usual directory
                    INSTALL_COMMAND   $(MAKE) install SILO_DIR=${Silo_source_dir} # Install directory, NOT in the usual directory
                    # -- Output control
                    ${Silo_logging_args})

# --- Useful variables for other packages that depend on Silo
set(Silo_DIR ${silo_install_dir})
