#  -*- mode: cmake -*-
#
# Build TPL: XSDK using Spack
#  

# --- Define all the directories and common external project flags
define_external_project_args(XSDK
                             TARGET xsdk
                             BUILD_IN_SOURCE )

# add version version to the autogenerated tpl_versions.h file
amanzi_tpl_version_write(FILENAME ${TPL_VERSIONS_INCLUDE_FILE}
    PREFIX XSDK
    VERSION 0 3 0 )

ExternalProject_Add(${XSDK_BUILD_TARGET}
    
    # The following 2 lines are only here because CMake will not allow
    # a build without at least these two variables defined (and BUILD_COMMAND).
    # However, they serve no real purpose for this particular build.

    # Should clone spack probably put spack in list of TPLs?
    DOWNLOAD_COMMAND ls
    
    CONFIGURE_COMMAND ls
    
    BUILD_COMMAND ${SPACK_BINARY} install xsdk 
    
    INSTALL_COMMAND ls
)

