#  -*- mode: cmake -*-

#
# Build TPL:  EcoSIM
#
# --- Define all the directories and common external project flags
define_external_project_args(ECOSIM
                             TARGET ecosim
                             DEPENDS HDF5 ZLIB NetCDF NetCDF_Fortran
                             BUILD_IN_SOURCE)

# add version to the autogenerated tpl_versions.h file
#include(${SuperBuild_SOURCE_DIR}/TPLVersions.cmake)
amanzi_tpl_version_write(FILENAME ${TPL_VERSIONS_INCLUDE_FILE}
                         PREFIX ECOSIM
                         VERSION ${ECOSIM_VERSION_MAJOR} ${ECOSIM_VERSION_MINOR} ${ECOSIM_VERSION_PATCH})

# --- Define the arguments passed to CMake.
# NOTE: hard-coded Debug here is necessary until CLM is safely working...
set(ECOSIM_CMAKE_CACHE_ARGS
      "-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}"
      "-DCMAKE_INSTALL_PREFIX:PATH=${TPL_INSTALL_PREFIX}"
      "-DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}"
      "-DCMAKE_Fortran_FLAGS:STRING=-fPIC -w -Wno-unused-variable -ffree-line-length-0 -O3"
      )

# --- If downloads are disabled point to local repository
if ( DISABLE_EXTERNAL_DOWNLOAD )
  STRING(REGEX REPLACE "/src/master" "" GIT_REPOSITORY_TEMP ${ECOSIM_GIT_REPOSITORY})
  STRING(REGEX REPLACE ".*\/" "" ECOSIM_GIT_REPOSITORY_LOCAL_DIR ${GIT_REPOSITORY_TEMP})
  set (ECOSIM_GIT_REPOSITORY_TEMP ${TPL_DOWNLOAD_DIR}/${ECOSIM_GIT_REPOSITORY_LOCAL_DIR})
else()
  set (ECOSIM_GIT_REPOSITORY_TEMP ${ECOSIM_GIT_REPOSITORY})
endif()
message(STATUS "ECOSIM git repository = ${ECOSIM_GIT_REPOSITORY_TEMP}")
message(STATUS "${ECOSIM_source_dir}")
message(STATUS "${TPL_INSTALL_PREFIX}")

# --- Add external project build and tie to the CLM build target
ExternalProject_Add(${ECOSIM_BUILD_TARGET}
                    DEPENDS   ${ECOSIM_PACKAGE_DEPENDS}           # Package dependency target
                    TMP_DIR   ${ECOSIM_tmp_dir}                   # Temporary files directory
                    STAMP_DIR ${ECOSIM_stamp_dir}                 # Timestamp and log directory
                    # -- Download and URL definitions
                    # -- Note: The repo is cloned into the ${ECOSIM_source_dir} directory
                    GIT_REPOSITORY ${ECOSIM_GIT_REPOSITORY_TEMP}
                    GIT_TAG        ${ECOSIM_GIT_TAG}
                    # -- Configure
                    SOURCE_DIR    ${ECOSIM_source_dir}            # Source directory
                    CONFIGURE_COMMAND ""
                    CMAKE_ARGS    ${AMANZI_CMAKE_CACHE_ARGS}   # Global definitions from root CMakeList
                                  ${ECOSIM_CMAKE_CACHE_ARGS}
                                  -DCMAKE_C_FLAGS:STRING=${Amanzi_COMMON_CFLAGS}  # Ensure uniform build
                                  -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
                                  -DCMAKE_CXX_FLAGS:STRING=${Amanzi_COMMON_CXXFLAGS}  # Ensure uniform build
                                  -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
                                  -DCMAKE_Fortran_FLAGS:STRING=${Amanzi_COMMON_FCFLAGS}
                                  -DCMAKE_Fortran_COMPILER:FILEPATH=${CMAKE_Fortran_COMPILER}
                    # -- Build
                    BINARY_DIR       ${TPL_INSTALL_PREFIX}          # Build directory
                    BUILD_COMMAND    make -f /global/home/users/agraus/code/ats_dev_dir/amanzi_tpls-build-master-Debug/ecosim/ecosim--source/Makefile config ATS=1 CC=${CMAKE_C_COMPILER} CXX=${CMAKE_CXX_COMPILER} FC=${CMAKE_Fortran_COMPILER}
                    # -- Install
                    INSTALL_DIR      ${TPL_INSTALL_PREFIX}     # Install directory
                    INSTALL_COMMAND  make -f /global/home/users/agraus/code/ats_dev_dir/amanzi_tpls-build-master-Debug/ecosim/ecosim--source/Makefile install ATS=1 CC=${CMAKE_C_COMPILER} CXX=${CMAKE_CXX_COMPILER} FC=${CMAKE_Fortran_COMPILER}
                    # -- Output control
                    ${ECOSIM_logging_args})

include(BuildLibraryName)
build_library_name(ecosim ECOSIM_LIB APPEND_PATH ${TPL_INSTALL_PREFIX}/lib)
set(ECOSIM_INCLUDE_DIRS ${TPL_INSTALL_PREFIX}/include)
set(ECOSIM_DIR ${TPL_INSTALL_PREFIX})
