#  -*- mode: cmake -*-

#
# Build TPL: NetCDF-Fortran
# 

# --- Define all the directories and common external project flags
define_external_project_args(NetCDF_Fortran TARGET netcdf-fortran
                             DEPENDS ${MPI_PROJECT} NetCDF)

# add version version to the autogenerated tpl_versions.h file
amanzi_tpl_version_write(FILENAME ${TPL_VERSIONS_INCLUDE_FILE}
  PREFIX NetCDF_Fortran
  VERSION ${NetCDF_Fortran_VERSION_MAJOR} ${NetCDF_Fortran_VERSION_MINOR} ${NetCDF_Fortran_VERSION_PATCH})
  
# --- Define the configure command
set(NetCDF_Fortran_CMAKE_CACHE_ARGS "-DCMAKE_INSTALL_PREFIX:FILEPATH=${TPL_INSTALL_PREFIX}")
list(APPEND NetCDF_Fortran_CMAKE_CACHE_ARGS "-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}")
list(APPEND NetCDF_Fortran_CMAKE_CACHE_ARGS "-DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}")
list(APPEND NetCDF_Fortran_CMAKE_CACHE_ARGS "-DENABLE_TESTS:BOOL=FALSE")

# --- Add external project build 
# Default build produces shared libraries
ExternalProject_Add(${NetCDF_Fortran_BUILD_TARGET}
	            DEPENDS ${NetCDF_Fortran_PACKAGE_DEPENDS} # Package dependency target
	            TMP_DIR ${NetCDF_Fortran_tmp_dir}         # Temporary files directory
	            STAMP_DIR ${NetCDF_Fortran_stamp_dir}     # Timestamp and log directory
	            # -- Downloads
	            DOWNLOAD_DIR ${TPL_DOWNLOAD_DIR}
	            URL ${NetCDF_Fortran_URL}                 # URL may be a web site OR a local file
	            URL_MD5 ${NetCDF_Fortran_MD5_SUM}         # md5sum of the archive file
		    DOWNLOAD_NAME ${NetCDF_Fortran_SAVEAS_FILE}  # file name to store
	            # -- Configure
	            SOURCE_DIR ${NetCDF_Fortran_source_dir}   # Source directory
                    CMAKE_CACHE_ARGS ${AMANZI_CMAKE_CACHE_ARGS}   # Global definitions from root CMakeList
                                     ${NetCDF_Fortran_CMAKE_CACHE_ARGS}
                                     ${Amanzi_CMAKE_C_COMPILER_ARGS}  # Ensure uniform build
                                     -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
                                     ${Amanzi_CMAKE_CXX_COMPILER_ARGS}
                                     -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
                                     ${Amanzi_CMAKE_Fortran_COMPILER_ARGS}
                                     -DCMAKE_Fortran_COMPILER:FILEPATH=${CMAKE_Fortran_COMPILER}
	            # -- Build
	            BINARY_DIR      ${NetCDF_Fortran_build_dir}  
	            BUILD_COMMAND   $(MAKE)                      # $(MAKE) enables parallel builds through make
	            BUILD_IN_SOURCE ${NetCDF_Fortran_BUILD_IN_SOURCE}
	            # -- Install
	            INSTALL_DIR ${TPL_INSTALL_PREFIX}
	            # -- Output control
	            ${NetCDF_Fortran_logging_args})


