#  -*- mode: cmake -*-

#
# Build TPL:  EXPRTK 
# This builds the chemistry component of PFlotran: exprtkchem.
#   
# --- Define all the directories and common external project flags
define_external_project_args(EXPRTK
                             TARGET exprtk
                             DEPENDS 
                             BUILD_IN_SOURCE)

# add version to the autogenerated tpl_versions.h file
amanzi_tpl_version_write(FILENAME ${TPL_VERSIONS_INCLUDE_FILE}
  PREFIX EXPRTK
  VERSION ${EXPRTK_VERSION_MAJOR} ${EXPRTK_VERSION_MINOR} ${EXPRTK_VERSION_PATCH})
  
# --- Define the install command
# Build the install script
set(EXPRTK_sh_install ${EXPRTK_prefix_dir}/exprtk-install-step.sh)
configure_file(${SuperBuild_TEMPLATE_FILES_DIR}/exprtk-install-step.sh.in
               ${EXPRTK_sh_install}
               @ONLY)

# Configure the CMake command file
set(EXPRTK_cmake_install ${EXPRTK_prefix_dir}/exprtk-install-step.cmake)
configure_file(${SuperBuild_TEMPLATE_FILES_DIR}/exprtk-install-step.cmake.in
               ${EXPRTK_cmake_install}
               @ONLY)
set(EXPRTK_INSTALL_COMMAND ${CMAKE_COMMAND} -P ${EXPRTK_cmake_install})

# --- Add external project build and tie to the EXPRTK build target
ExternalProject_Add(${EXPRTK_BUILD_TARGET}
                    DEPENDS   ${EXPRTK_PACKAGE_DEPENDS}        # Package dependency target
                    TMP_DIR   ${EXPRTK_tmp_dir}                # Temporary files directory
                    STAMP_DIR ${EXPRTK_stamp_dir}              # Timestamp and log directory
                    # -- Download and URL definitions
                    DOWNLOAD_DIR ${TPL_DOWNLOAD_DIR}
                    URL          ${EXPRTK_URL}                 # URL may be a web site OR a local file
                    URL_MD5      ${EXPRTK_MD5_SUM}             # md5sum of the archive file
                    # -- Patch 
                    # PATCH_COMMAND ${EXPRTK_PATCH_COMMAND}
                    # -- Configure
                    SOURCE_DIR    ${EXPRTK_source_dir}         # Source directory
                    CONFIGURE_COMMAND ""
                    CMAKE_ARGS    ${AMANZI_CMAKE_CACHE_ARGS}   # Ensure uniform build
                    # -- Build
                    BUILD_COMMAND    ""
                    BUILD_IN_SOURCE  1                         # Flag for in source builds
                    # -- Install
                    INSTALL_DIR      ${TPL_INSTALL_PREFIX}     # Install directory
                    INSTALL_COMMAND  ${EXPRTK_INSTALL_COMMAND} 
                    # -- Output control
                    ${EXPRTK_logging_args})

set(EXPRTK_INCLUDE_DIRS ${TPL_INSTALL_PREFIX}/include)
set(EXPRTK_DIR ${TPL_INSTALL_PREFIX})

