// Emacs Mode Line: -*- Mode:c++;-*-
// -------------------------------------------------------------
/**
 * @file   FrameworkTraits.hh
 * @author William A. Perkins
 * @date Fri Mar 18 15:18:51 2011
 * 
 * @brief  
 * 
 * 
 */
// -------------------------------------------------------------
// -------------------------------------------------------------
// Created March 10, 2011 by William A. Perkins
// Last Change: Fri Mar 18 15:18:51 2011 by William A. Perkins <d3g096@PE10900.pnl.gov>
// -------------------------------------------------------------
#ifndef _FrameworkTraits_hh_
#define _FrameworkTraits_hh_

#include <Epetra_Comm.h>
#include <Teuchos_RCP.hpp>

#include "MeshFramework.hh"
#include "MeshFileType.hh"
#include "Mesh_maps_base.hh"


namespace Mesh {

  /// Is the specified framework available
  extern bool framework_available(const Framework& f);

  /// General routine to see if a format can be read by particular framework
  extern bool framework_reads(const Framework& f, const Format& fmt, const bool& parallel);

  /// Read a mesh
  extern Teuchos::RCP<Mesh_maps_base> 
  framework_read(Epetra_MpiComm& comm, const Framework& f, const std::string& fname);

  /// General routine to see if a mesh can be generated by a particular framework
  extern bool framework_generates(const Framework& f, const bool& parallel);

  /// Generate a mesh
  extern Teuchos::RCP<Mesh_maps_base> 
  framework_generate(Epetra_MpiComm& comm, const Framework& f, 
                     const double& x0, const double& y0, const double& z0,
                     const double& x1, const double& y1, const double& z1,
                     const unsigned int& nx, const unsigned int& ny, const unsigned int& nz);


} // namespace Mesh

#endif
