!
! THIS FILE WAS GENERATED BY make_defines DO NOT EDIT
!

module ats_defines

   use, intrinsic :: ISO_C_BINDING
   use :: ats_data

      integer(int32_t), bind(C, name='ATS_SUCCESS') :: ATS_SUCCESS
      integer(int32_t), bind(C, name='ATS_MPI_ERROR') :: ATS_MPI_ERROR

end module ats_defines
