name: Build TPL images

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
  push:
    paths:
      - 'config/Superbuild/**'
      - 'tools/**'

jobs:
  build-tpl-image:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
    runs-on: ${{matrix.os}}
    steps:
    - name: Check out the Amanzi repo
      uses: actions/checkout@v4
    - name: Get TPLs version
      id: version
      working-directory: Docker
      run: |
        echo "AMANZI_TPLS_VER=$(./get_tpls_version.sh)" >> $GITHUB_ENV
        echo "TPLs version = ${{env.AMANZI_TPLS_VER}}"
    - name: Get runner architecture
      run: |
        if [[ ${{matrix.os}} == "ubuntu-24.04-arm" ]]; then
          echo "ARCH=arm64" >> $GITHUB_ENV
        else
          echo "ARCH=amd64" >> $GITHUB_ENV
        fi
    - name: Extract the branch name
      id: branch
      run:
        echo "AMANZI_BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV
    - name: Filter the branch name to generate a tag for Docker
      id: tag
      run:
        echo "AMANZI_BRANCH_TAG=$(echo ${{env.AMANZI_BRANCH}} | sed -e 's/\//--/g')" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Docker/Dockerfile-TPLs
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/amanzi-tpls:${{env.AMANZI_TPLS_VER}}-${{env.ARCH}}-mpich
        build-args: |
          amanzi_branch=${{env.AMANZI_BRANCH}}
          trilinos_ver="15-1-0"
          petsc_ver="3.21"

  fix-manifest:
    runs-on: ubuntu-latest
    needs: build-tpl-image
    if: success()
    steps:
      - name: Check out the Amanzi repo
        uses: actions/checkout@v4
      - name: Get TPLs version
        id: version
        working-directory: Docker
        run:
          echo "AMANZI_TPLS_VER=$(./get_tpls_version.sh)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Pull images (remove with artifacts??)
        run: |
          docker pull ${{secrets.DOCKERHUB_USERNAME}}/amanzi-tpls:${{env.AMANZI_TPLS_VER}}-arm64-mpich
          docker pull ${{secrets.DOCKERHUB_USERNAME}}/amanzi-tpls:${{env.AMANZI_TPLS_VER}}-amd64-mpich
      - name: Edit manifest
        run: |
          docker manifest create ${{secrets.DOCKERHUB_USERNAME}}/amanzi-tpls:${{env.AMANZI_TPLS_VER}}-mpich \
            --amend ${{secrets.DOCKERHUB_USERNAME}}/amanzi-tpls:${{env.AMANZI_TPLS_VER}}-amd64-mpich \
            --amend ${{secrets.DOCKERHUB_USERNAME}}/amanzi-tpls:${{env.AMANZI_TPLS_VER}}-arm64-mpich
          docker manifest push ${{secrets.DOCKERHUB_USERNAME}}/amanzi-tpls:${{env.AMANZI_TPLS_VER}}-mpich
